In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("Iris.csv")

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [4]:
dataset.shape

(150, 6)

In [5]:
dataset.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
dataset.info

<bound method DataFrame.info of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-seto

In [7]:
dataset[30:60]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
30  31            4.8           3.1            1.6           0.2   
31  32            5.4           3.4            1.5           0.4   
32  33            5.2           4.1            1.5           0.1   
33  34            5.5           4.2            1.4           0.2   
34  35            4.9           3.1            1.5           0.1   
35  36            5.0           3.2            1.2           0.2   
36  37            5.5           3.5            1.3           0.2   
37  38            4.9           3.1            1.5           0.1   
38  39            4.4           3.0            1.3           0.2   
39  40            5.1           3.4            1.5           0.2   
40  41            5.0           3.5            1.3           0.3   
41  42            4.5           2.3            1.3           0.3   
42  43            4.4           3.2            1.3           0.2   
43  44            5.0           3.5            1.6           0.6   
44  45            5.1           3.8            1.9           0.4   
45  46            4.8           3.0            1.4           0.3   
46  47            5.1           3.8            1.6           0.2   
47  48            4.6           3.2            1.4           0.2   
48  49            5.3           3.7            1.5           0.2   
49  50            5.0           3.3            1.4           0.2   
50  51            7.0           3.2            4.7           1.4   
51  52            6.4           3.2            4.5           1.5   
52  53            6.9           3.1            4.9           1.5   
53  54            5.5           2.3            4.0           1.3   
54  55            6.5           2.8            4.6           1.5   
55  56            5.7           2.8            4.5           1.3   
56  57            6.3           3.3            4.7           1.6   
57  58            4.9           2.4            3.3           1.0   
58  59            6.6           2.9            4.6           1.3   
59  60            5.2           2.7            3.9           1.4   

            Species  
30      Iris-setosa  
31      Iris-setosa  
32      Iris-setosa  
33      Iris-setosa  
34      Iris-setosa  
35      Iris-setosa  
36      Iris-setosa  
37      Iris-setosa  
38      Iris-setosa  
39      Iris-setosa  
40      Iris-setosa  
41      Iris-setosa  
42      Iris-setosa  
43      Iris-setosa  
44      Iris-setosa  
45      Iris-setosa  
46      Iris-setosa  
47      Iris-setosa  
48      Iris-setosa  
49      Iris-setosa  
50  Iris-versicolor  
51  Iris-versicolor  
52  Iris-versicolor  
53  Iris-versicolor  
54  Iris-versicolor  
55  Iris-versicolor  
56  Iris-versicolor  
57  Iris-versicolor  
58  Iris-versicolor  
59  Iris-versicolor

In [8]:
dataset.replace({"Iris-virginica":2,"Iris-setosa":1, "Iris-versicolor":0},inplace=True)

In [9]:
dataset["Species"]=dataset["Species"].astype(int)

In [10]:
x=dataset[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]
y=dataset["Species"]

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    int32  
dtypes: float64(4), int32(1), int64(1)
memory usage: 6.6 KB


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test,y_train,y_test=train_test_split(x,y,train_size=0.7, random_state=1222)

In [14]:
y_test.info()

<class 'pandas.core.series.Series'>
Index: 45 entries, 118 to 15
Series name: Species
Non-Null Count  Dtype
--------------  -----
45 non-null     int32
dtypes: int32(1)
memory usage: 540.0 bytes


In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model=LinearRegression()

In [17]:
model.fit(x_train,y_train)

LinearRegression()

In [18]:
from sklearn.metrics import mean_absolute_percentage_error

In [19]:
y_pred=model.predict(x_test)

In [20]:
y_pred=y_pred.astype(int)

In [21]:
mean_absolute_percentage_error(y_test,y_pred)

600479950316066.5

In [22]:
y.shape

(150,)

In [23]:
x.shape

(150, 4)

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
model1=DecisionTreeClassifier()

In [26]:
model1.fit(x_train,y_train)

DecisionTreeClassifier()

In [27]:
y_pred1=model1.predict(x_test)

In [28]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_pred1)

200159983438688.72

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

0.9777777777777777

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(y_test,y_pred1)

array([[14,  0,  1],
       [ 0, 16,  0],
       [ 0,  0, 14]], dtype=int64)

RandomForest

In [39]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()

In [40]:
model2.fit(x_train,y_train)

RandomForestClassifier()

In [41]:
y_pred2=model2.predict(x_test)

In [42]:
y_pred2

array([2, 1, 2, 2, 0, 1, 0, 0, 0, 2, 1, 2, 0, 0, 2, 2, 1, 0, 2, 1, 0, 1,
       2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 2, 0,
       1])

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

0.9777777777777777

In [44]:
from sklearn.svm import SVR

In [45]:
model3=SVR()

In [46]:
model3.fit(x_train,y_train)

SVR()

In [51]:
y_pred3=model3.predict(x_test)

In [54]:
y_pred3=y_pred3.astype(int)

In [55]:
y_pred3

array([2, 0, 2, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1])

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred3)

0.5333333333333333

In [65]:
from sklearn.neighbors import KNeighborsClassifier

In [72]:
model4=KNeighborsClassifier(n_neighbors=7 )

In [73]:
model4.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [74]:
y_pred4=model4.predict(x_test)

In [75]:
y_pred4

array([2, 1, 2, 2, 0, 1, 0, 0, 0, 2, 1, 2, 0, 0, 2, 2, 1, 0, 2, 1, 0, 1,
       2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0,
       1])

In [77]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred4,y_test)

0.9777777777777777